[package]
name = "mcon"
authors = ["MagicTeaMC <maoyue@maoyue.tw>"]
description = "Config Minecraft server.properties file faster!"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
chrono = "0.4"
colored = "3.0.0"